import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';

import '../../../../core/router/app_routes.dart';
import '../../../../core/theme/app_theme.dart';
import '../../../../core/theme/brand_assets.dart';
import '../../../../core/theme/spacing.dart';
import '../../../../core/widgets/comic_mascot.dart';
import '../providers/auth_session_provider.dart';

/// Brief branded splash; navigates to login or home based on auth session.
///
/// Background is the seed teal (not the theme surface) so it matches the
/// native launch screen generated by flutter_native_splash.
class SplashScreen extends ConsumerStatefulWidget {
  const SplashScreen({super.key});

  @override
  ConsumerState<SplashScreen> createState() => _SplashScreenState();
}

class _SplashScreenState extends ConsumerState<SplashScreen> {
  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addPostFrameCallback((_) => _navigateAway());
  }

  Future<void> _navigateAway() async {
    await Future<void>.delayed(const Duration(milliseconds: 1100));
    if (!mounted) return;

    final isAuthenticated = ref.read(authSessionProvider);
    context.go(isAuthenticated ? AppRoutes.home : AppRoutes.login);
  }

  @override
  Widget build(BuildContext context) {
    const onTeal = Colors.white;

    return Scaffold(
      backgroundColor: AppTheme.seedColor,
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            const ComicMascot(
              asset: BrandAssets.mascotWave,
              size: 160,
              heroTag: BrandAssets.mascotHeroTag,
            ),
            const SizedBox(height: Spacing.md),
            Text(
              'Medico',
              style: Theme.of(context).textTheme.headlineMedium
                  ?.copyWith(color: onTeal, fontWeight: FontWeight.w800),
            ),
            const SizedBox(height: Spacing.sm),
            Text(
              'MBBS exam prep',
              style: Theme.of(context).textTheme.bodyLarge
                  ?.copyWith(color: onTeal.withValues(alpha: 0.82)),
            ),
            const SizedBox(height: Spacing.xl),
            const CircularProgressIndicator(color: onTeal),
          ],
        ),
      ),
    );
  }
}
